### ISSUE TITLE
Automatic redeployment (hot swap) causes an exception on MprServlet

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/multiplatform-runtime#19]
When using hot swap to quickly redeploy the application when saving (in development time), like what is used in the Bakery starter, the deployment fails due to an exception on the `init` method of the `MprServlet`:

```
java.lang.IllegalArgumentException: A fallback resolver for the type class com.vaadin.server.VaadinService is already defined.
	at com.vaadin.util.CurrentInstance.defineFallbackResolver(CurrentInstance.java:154) ~[vaadin-server-8.6-SNAPSHOT.jar:8.6-SNAPSHOT]
	at com.vaadin.mpr.AbstractMprServlet.init(AbstractMprServlet.java:60) ~[mpr-core-1.0-SNAPSHOT.jar:na]
	at javax.servlet.GenericServlet.init(GenericServlet.java:158) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:205) ~[vaadin-server-8.6-SNAPSHOT.jar:8.6-SNAPSHOT]
```
This makes the hot swap not possible to be used when MPR is on the classpath.

**Comment by javier-godoy** [comment]
This issue is caused by spring-boot-devtools [automatically restarting the application](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-restart) when it detects a change. I had a better experience by removing `spring-boot-devtools` dependency from the POM, and relying on the hot deploy feature provided by the IDE.

**Comment by denis-anisimov** [comment]
Could you please provide steps to reproduce ?

**Comment by KyleRogers** [comment]
This issue is linked on the [limitations page for Vaadin MPR](https://vaadin.com/docs/v10/mpr/configuration/limitations.html). Could you please document the state of this issue and clarify affected scenarios and workarounds?

- Was this issue solved or does it persist and was classified as "won't fix"?
- Does this issue effect hot swap using IDEs such as Eclipse or IntelliJ?
- Or does this issue effect automatic restarts by spring dev-tools only?
