### ISSUE TITLE
Support multiple UIs as legacy components inside MPR

### ISSUE THREAD

**Issue by pleku** [vaadin/multiplatform-runtime#45]
When using MPR with V7 / V8 application, I should be able to add any number of my legacy V7 / V8 UIs inside the Flow app using MPR, because I just want to get the UIs to run inside V10 without making "any" changes to those.

Some implementation specifics to take into consideration:
- the legacy UI will have a URL that it is accessed from
  - that URL should be specified somehow, either its read from where ever it has been specified in v7, or we require the users to register it by adding some code into their legacy UI
- Any `Navigator` set inside the legacy `UI` should work, meaning that navigator API should work
  - it should be fine to require the user to change the Navigator to something else provided by MPR, as long as that extends the original `Navigator` from v7/v8
- Any `Page` calls done through the `UI` should work
- The `UI` is a `CDIUI` which means that this feature should work with CDI
- the `init(VaadinRequest request)` method must be called when the UI is opened the first time
  - thus it is fine to force the navigation between UI's to cause a complete page refresh

One limitation to consider is that when the legacy UI is shown, there is nothing from Flow side visible - when using this feature, the user cannot have anything based on Flow visible on the screen at the same time.

**Comment by Legioth** [comment]
Which instance should be returned by `com.vaadin.ui.UI.getCurrent()`?

**Comment by pleku** [comment]
To my understanding it should dependent on the import. If the user doesn't change their code, it imports the legacy UI.

There is a good chance that `getUI` calls cast the returned `UI` into something more specific which has some API that they depend on. They don't need the Flow UI in this case.

**Comment by Legioth** [comment]
What I mean is that if there are multiple UIs, then which of them should `getCurrent()` return?

**Comment by pleku** [comment]
>What I mean is that if there are multiple UIs, then which of them should `getCurrent()` return?

There can only be one UI active at a time, which 1) `MyLegacyUI` extends MprSpecialUI`
2) `MyExtendingUI` extends AbstractLegacyUI`

**Comment by Legioth** [comment]
> when the legacy UI is shown, there is nothing from Flow side visible
> it is fine to force the navigation between UI's to cause a complete page refresh

Why is MPR used at all in that case?

> the legacy UI will have a URL that it is accessed from

Why not instead let a regular V7 / V8 servlet handle requests for such URLs, and there there might be a Flow servlet in the same context that is mapped to different URLs and handles those?

**Comment by Legioth** [comment]
Based on the idea that a specific URL would open a V7 / V8 UI as-is in the browser without showing anything from the Flow side, it seems like a much simpler solution would be to just deploy `VaadinServlet` from Vaadin 7 / 8 side-by-side with `VaadinServlet` from Flow. It's probably most straightforward to let the Flow servlet deploy itself for `/*` and handle generic bootstrapping as long as there's a matching `@Route`. The V7 / V8 servlet would then be mapped to all the specific URLs for which there are corresponding UI instances.

Some specific details to look out for:
* Some special URL patterns such as `/VAADIN/` might have to be remapped since both V7 / V8 and Flow use the same namespace.
* Should ensure each servlet gets a unique "service name" so that they use separate keys. I think this will be the case by default, but I'm not 100% sure.
