### ISSUE TITLE
PreserveOnRefresh is broken with MPR

### ISSUE THREAD

**Issue by pleku** [vaadin/multiplatform-runtime#85]
Based on https://github.com/vaadin/multiplatform-runtime-internal/issues/473.

Apparently v7 and v8 framework code, the parts used with MPR, writes its own `window.name` and thus it breaks flow `@PreserveOnRefresh` feature since tha name doesn't match what is expected from Flow side.

Fixing this requires probably changes to both v7 and v8 to be able to tell it to "not touch window.name". Another option would be to just fix it in Flow by using something else than `window.name` for preserve-on-refresh, at least when MPR is used (no I don't know what it would be).

**Comment by mletenay** [comment]
I don't think plain v7 and v8 are to blame with messing the window.name.
As I mentioned in vaadin/flow#11279, the (changing) window name is a UUID.
So I followed its trail, put a breakpoint to UUID constructor and came to suspicion that it's actually MPR code which does this bad name changing.
The MPR sources are unfortnutelly not avaliable  ;-(, but the same UUID which is set to window.name gets created within
`AbstractLegacyWrapper#initContent`.
So maybe instead of setting random UUID there, the actual windows.name should be used there.
Which I guess should already be present in Flow UI (e.g. via `ui.getInternals().getExtendedClientDetails().getWindowName()`).
And the PreseserveOnRefresh may be easily fixed within MPR code.

**Comment by TatuLund** [comment]
The fixes are merged and will be released in the next version.
